### ISSUE TITLE
[Feature Request] Monospace font for relevant input fields in options

### ISSUE THREAD

**Issue by disco0** [sixcious/infy-scroll#10]
It'd be nice to have a monospace font (or just `monospace`, save for a configurable option) for `textarea` fields expecting code, or code-like text—e.g. the Database Blacklist and other fields receiving regexes, and maybe Next Rule in the popup. I thought about a custom CSS input option similar to Tampermonkey as an larger scope alternative, but that seems somewhat overkill as the current UI is pretty great to use otherwise.

**Screenshots**

> If applicable, please add any screenshots that might help explain your feature request better. **However, please do not post any screenshots of the extension.**

Hopefully a screenshot of just the content of a text box is fine for reference? I'll remove the before if requested.

##### Current:

<img src="https://user-images.githubusercontent.com/13393582/125153861-7c3a0880-e10b-11eb-8002-32f35b727117.png" height="150px" top="-10px">

##### Monospaced:

<img title="font-family: Iosevka Extended; font-size: 14px; line-height: [1.35x font-size]" src="https://user-images.githubusercontent.com/13393582/125153717-8c051d00-e10a-11eb-9f95-6cbd77b4da0f.png" height="150px">

**Comment by roysix** [comment]
Hi disco0! Thanks for using Infy Scroll and for opening this issue!

I'd love to implement this for you, but I'm not sure how this would work out long-term. Infy uses Material Design for its UI, which uses the Roboto font by default, and I've been trying lately to make the least amount of custom changes to the UI whenever possible. Roboto is a more slender/thinner font, so we can fit more characters when both fonts are at the same height size, which is really needed in the Popup due to the limited amount of width size there is to work with. Monospace is a bit easier on the eyes though. I'll definitely consider adding this in the future as an optional feature, especially if more people want this. I just need to think about it from a long-term perspective, as I'd hate to have to remove it or keep maintaining it if in the off chance it messes with the text fields in a random future Material Design update.

Thanks again for bringing this issue up and for using Infy!

**Comment by sixcious** [comment]
Hi, I've finally added support for Roboto Mono font for all inputs and paths in Version 8.

Thanks for making this feature request! 💜
