### ISSUE TITLE
Add Infy Scroll in Context Menu

### ISSUE THREAD

**Issue by Arun10752** [sixcious/infy-scroll#102]
### Description

![010110100010101010100101001010101001011](https://github.com/user-attachments/assets/925d7b77-b90e-45ff-bbd1-57fb11255a03)

Add Infy Scroll to Context menu where clicking it once activates the feature and shows a tick mark on it and clicking it again, deactivates the auto pagerize feature and turns off tick mark or simply add ON and off as sub options, currently uautopagerize does not work for some websites, infy works on them , Awesome job, i want to activate it fast and Manage both extensions fastly whenever one fails to work on any specific site.

Hopefully Next update is Released Fast, atleast minor update with just this feature.

Thanks.

### URL

https://github.com/

### Version

Version 0.8 β

### Browser

Brave Browser

### OS

Windows 8.1

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related to the app and is not related to making it work with a specific website (including [how to make images load](https://github.com/sixcious/infy-scroll/wiki/Missing-Images-or-Blank-Pages))

**Comment by Arun10752** [comment]
The context option can be named as "Activate Infy" where once clicked and tick mark comes near to the right of Activate infy means infy is on and if while "Activate infy tick mark" is shown and clicked again, infy goes off.

**Comment by sixcious** [comment]
Hi once again Arun, thanks so much. I actually added full support for Context menu shortcuts a long time ago in Version 8.0. That was actually based on your feedback from earlier this year. Infy Scroll 8.0 requires Chrome 120 and higher. I'm guessing you aren't able to update your browser and operating system because Chromium 109 is the highest version supported in Windows 8.1?

**Comment by Arun10752** [comment]
yes chromium 109 

v1.47.186 in brave browser

**Comment by Arun10752** [comment]
yes i think its because of old version

Just checked the store,

For other Extensions, No Warning Messages
![Untitled111111111111111111111](https://github.com/user-attachments/assets/cd36ec9a-9ac7-4ae2-9fb9-a15e1c42f618)

For Infy
![Untitled11111111111](https://github.com/user-attachments/assets/799ce78c-e94a-4275-a100-9e28e3dfe6d8)

I guess if infy gets uninstalled, we wont be able to install it via chrome store anymore, we have to follow load unpacked but i will make sure infy doesnt get installed, maybe you can release infy lite with all of the feature requests i asked as i believe the ones which i asked recently does not require latest chromium, maybe you have added other features which may require latest but for the ones which i asked and for the ones which you believe can be implemented for chromium 109, you can release a new extension Infy Scroll for Legacy Chrome Builds(Chromium 109).

Maybe its too much to ask but just wanted to tell you this so People who use older windows versions can get little bit of updates instead of completely no updates...

**Comment by alexolog** [comment]
Is there support in Firefox?

**Comment by sixcious** [comment]
Thank you Arun, I'll consider this in the future. I would really encourage you to update your OS and browser — not just so you can use Infy — but so you get security updates. Though, I'm sure you have your reasons and you may not have any control over it and I do empathize with you. I really can't provide any support on doing this, but if you can download the CRX file from the web store and try lowering the minimum version in the manifest file from 120 to 109 and then load it as an unpacked extension, it might work.

And yes Alex, context menu shortcuts are also in the latest Firefox version. They're under OPTIONS > SHORTCUTS.

I'm going to go ahead and close this for now since this feature is technically in Infy.

Thank you so much again for suggesting this feature! 💜
