### ISSUE TITLE
Page Divider Needs Customization

### ISSUE THREAD

**Issue by Arun10752** [sixcious/infy-scroll#103]
### Description

i want page divider to be ON for X set of sites and page divider to be OFF for another X set of sites, So instead of only global Yes or No, Allow us to edit domains for which page divider should be shown and Edit domains for which the page divider should be turned off. By this way, we dont have to manually enter settings page every time, Thanks.

### URL

https://github.com/

### Version

Version 0.8 β

### Browser

Brave Browser

### OS

Windows 8.1

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related to the app and is not related to making it work with a specific website (including [how to make images load](https://github.com/sixcious/infy-scroll/wiki/Missing-Images-or-Blank-Pages))

**Comment by sixcious** [comment]
Hi again Arun, thanks for opening this issue. You should already be able to do this on a per-site basis. Just save the URLs you want to change your divider preference for and then go to OPTIONS > SAVES and add the `pageDivider` key with either a `yes` or a `no` value. Here's the link to the [page in the Help Guide](https://github.com/sixcious/infy-scroll/wiki/Saves#save-format) that explains how to do this and lists all the different settings and values in case you want to change any other settings.

Please feel free to let me know if you still need help.

**Comment by Arun10752** [comment]
> Hi again Arun, thanks for opening this issue. You should already be able to do this on a per-site basis. Just save the URLs you want to change your divider preference for and then go to OPTIONS > SAVES and add the `pageDivider` key with either a `yes` or a `no` value. Here's the link to the [page in the Help Guide](https://github.com/sixcious/infy-scroll/wiki/Saves#save-format) that explains how to do this and lists all the different settings and values in case you want to change any other settings.
> 
> Please feel free to let me know if you still need help.

![20241219_0342531111111](https://github.com/user-attachments/assets/7ce4e7f1-ed38-4712-bbda-91b86d8c7c13)

**Comment by sixcious** [comment]
Hi again Arun, OK so luckily that's just a simple syntax error involving commas. You were missing a comma at the end of the `"date"` line, and you had a comma on the last `"pageDivider"` line that you should remove. The last line should not have a comma at the end.

I recommend that you just delete this save and start over:
1. Visit the website in question in your browser (in case it already has Database URL settings for it)
2. Open Infy's UI Window and click the Heart Button in the top-right corner (which is now a Star Button in Version 8.0+) and then ACCEPT to save the URL with the database settings already applied to it
3. Go to OPTIONS > SAVES and edit the save there and just add the `"pageDivider": "yes"` at the very end (with no comma as it will be the last line before the last squiggly brace).

(Apologies, but I had to remove your screenshot due to the URL.)

**Comment by Arun10752** [comment]
![Untitled1111111111111](https://github.com/user-attachments/assets/ab3c68e6-aace-4c76-b629-eef1f7da22e4)

worked, thanks
