### ISSUE TITLE
[Feature Request] Add a Backup and Restore Feature

### ISSUE THREAD

**Issue by HarlockHomes** [sixcious/infy-scroll#17]
**Describe the feature request you'd like**
When I open the portable version of Chrome under the new Windows 10 or 11, the "save" under Infy Scroll Options is empty.
This kind of experience is not good, after all, it was created and preserved with great effort before.
The data saved by some other extension programs can still be valid, such as
Tab Session Manager, uBlock, Tampermonkey, SwithyOmega.
uBlock saves the settings in the cloud, and Tab session Manager saves it locally. These experiences are all very good.
In addition, is it possible for users to submit custom rules to the database?

**Comment by sixcious** [comment]
Hi again, thanks for using Infy and for opening this issue.

I'm sorry for the poor experience regarding Saved URLs. It sounds like you want the ability to export Saved URLs between different Chrome installations of Infy Scroll.

I designed Infy to only save data locally because I treat your Saved URLs like sensitive data and because the sync storage has far less space available than local.

Re: Exporting/Importing data
Because Infy is still in beta and because I am still adding more and more properties to the saved URLs, I haven't yet finalized adding a "built-in" way to export/import saves locally. I do provide a method to do this using the console here though.

Re: Contributing to the AutoPagerize Database
Yes, it is possible to submit rules, but the database isn't managed by me (it's managed by the AutoPagerize/Wedata owners) and it uses OpenID for authentication, which makes it hard to get in as OpenID is being phased out. If you email me privately, I can send you a link to an OpenID provider that still works.

Hope this helps!

**Comment by sixcious** [comment]
Hi again,

This feature has now been added in Version 0.7, which is now live on all the web stores. You can find it under `Options > Backup`. If you still notice an issue after updating Infy to 0.7, let me know and I'll reopen this.

Thanks again for reporting this issue and sorry for the inconvenience!
