### ISSUE TITLE
Some content is invisable due to scale and crop

### ISSUE THREAD

**Issue by jiang-yuan** [sixcious/infy-scroll#19]
**Describe the bug**
I like the functions of this pluin. I am using edge edition.
When I click infy Scroll button on the tool button of my browser, right and bottom part content is invisable due to scale and crop. I cannot do right operations in this situation.
I try to resize visiting page to 100% but it does not affect scale rate of this extension.

**URL**
For all urls

**Environment**
If you can, please fill out as much as you can about your environment.
 - Device: PC
 - OS: Windows 10
 - Browser Edge
 - Browser Version 95
 - Extension Version 0.6.06

**Comment by sixcious** [comment]
Hi, thanks for using Infy and for opening this issue!

I'm sorry that's happening. This will be addressed in the next release. Infy currently tries to use the maximum 800 x 600 pixel space the Popup Window has available, and I think some people's Windows Display settings are set in a way that you start seeing scrollbars show up.

Here are some things to try in the mean time:
1. Try going to Infy Scroll's Options Screen by clicking the `GEAR` Icon and under the `UI` Section, change the `UI Image` from `Infy` to `Infinity`.
2. Try adjusting your Windows 10 Display Settings temporarily (try lowering the "percentage" value)

Could you help me by telling me what your Windows 10 Display Settings are, like in the screenshot below?

![Windows Display Settings](https://user-images.githubusercontent.com/1027814/147857349-47496cfa-6dbb-40b3-8a5e-3df159ae1ba3.JPG)

**Comment by jiang-yuan** [comment]
![image](https://user-images.githubusercontent.com/36291537/147857502-53a09fb3-da11-41e6-9715-5faceba6bdab.png)
(Sorry, I am using CN in my OS)

100% zoom
34 inches 2560 x 1080 resolution

**Comment by sixcious** [comment]
No problem! I don't have 2560 x 1080 as an option available for me to test on my monitor. It looks like that's a 21:9 aspect ultrawide. Are you able to lower the percentage any lower from 100% temporarily? This is pretty strange because on my regular 1920 x 1080 monitor at 100%, I don't have this issue. The only way I can replicate this on my monitor is if I either increase the Windows Display percentage or the Edge `Page zoom` to a high percentage.

Did you already try lowering the "Global" Edge `Page zoom` percentage (the global zoom setting as shown in the screeshot below, not the individual tab zoom) to see if it helps temporarily?

![Edge Zoom](https://user-images.githubusercontent.com/1027814/147858098-ae62cf82-aee4-441f-a0dd-a3f6e3333c66.JPG)

**Comment by jiang-yuan** [comment]
I try to change the global page zoom at edge 'apprearance' setting to 100% and restart my browser, it looks fine now. 
(only change page zoom for current page does not work)
I think this may becasue the zoom percentage of this extension's content is inherit from the browser setting.

**Comment by jiang-yuan** [comment]
> No problem! I don't have 2560 x 1080 as an option available for me to test on my monitor. It looks like that's a 21:9 aspect ultrawide. Are you able to lower the percentage any lower from 100% temporarily? This is pretty strange because on my regular 1920 x 1080 monitor at 100%, I don't have this issue. The only way I can replicate this on my monitor is if I either increase the Windows Display percentage or the Edge `Page zoom` to a high percentage.
> 
> Did you already try lowering the "Global" Edge `Page zoom` percentage (the global zoom setting as shown in the screeshot below, not the individual tab zoom) to see if it helps temporarily?
> 
> ![Edge Zoom](https://user-images.githubusercontent.com/1027814/147858098-ae62cf82-aee4-441f-a0dd-a3f6e3333c66.JPG)

But I need to zoom my pages to 110% otherwise the font is small for me. This problem isn't resolved. Hope you will fix it in next version. Thank you.

**Comment by sixcious** [comment]
Hi again,

I understand. The reason why you're running into this issue is because I had added CSS that ensures horizontal scrollbars always remain hidden. I never tried using a zoom higher than the default 100% in my testing and didn't know it'd be an issue. I had already removed that CSS in my local build before you posted this issue for a different reason, so you should find it usable in the next release (you'll just start seeing a horizontal scrollbar).

We can keep this issue open until the next version is released, although I'm not sure when that will be...

Thanks for your understanding and patience!

**Comment by sixcious** [comment]
Hi again,

This has now been addressed in Version 0.7, which is now live on all the web stores. If you still notice an issue after updating Infy to 0.7, let me know and I'll reopen this.

Thanks again for reporting this issue!
