### ISSUE TITLE
Site images not loading (Fix Element Iframe insertion point)

### ISSUE THREAD

**Issue by Tanookirby** [sixcious/infy-scroll#21]
I found a site where images will not load for the appended pages. Can this be corrected?

https://www.eonline.com/news/page/3

 - Device: Dell PC
 - OS: Windows 10 (64-bit)
 - Browser: Firefox 96.0.1 (64-bit)

**Comment by sixcious** [comment]
Hi Tanookirby, thanks for using Infy and for opening this issue!

For that site, since it seems to be a Database URL already, I would try checking the `Element Iframe` checkbox. That seemed to work for me at least.

Also, if you don't mind me asking, are you the same Tanookirby who has contributed like hundreds of times to the AutoPagerize Database?! (If so, I just wanted to say thank you!)

**Comment by Tanookirby** [comment]
Your welcome, and i tried the Element Iframe checkbox. It's effective, but I noticed it adds the elements after the <nav> element with the page instead of before it. Do you know why?

**Comment by sixcious** [comment]
Hi again Tanookirby, apologies for the delay, I totally missed this one.

I haven't worked on that part of the iframe code base in well over a year, but I took a look just now and it's because it's always recalculating the insertion point to be the last node of the parent (unnecessarily), and not actually using the last page element's next sibling.

I think this might be a one liner fix, and just calls for editing out this line:
https://github.com/sixcious/infy-scroll/blob/main/src/base/js/scroll.js#L512

I'll try and have it patched up in the next version.

Thanks for reporting this, I would have never noticed it!

**Comment by knight88m** [comment]
Same problem here, it wont load images on ebay-kleinanzeigen.de

**Comment by sixcious** [comment]
Hi @knight88m

Sorry the images aren't loading for you. The ebay-kleinanzeigen.de site uses scripts to load its images, so you need to use an Iframe append mode so it can run the scripts needed for each page. If you're on Version 0.7, try changing the append mode to the regular Iframe mode.

Also, because this site disallows iframes, you'll need to add another extension that can allow Infy to append iframes. You can find a few in the web store, for example [Framer](https://chrome.google.com/webstore/detail/framer-make-iframes-possi/adohambhfalbpaenaclmhhjhilmakmoo). If you know how to install extensions locally, you can also try using [Xframey](https://github.com/sixcious/xframey) (developed by me).

I saw your review, so please let me know if this helps.

**Comment by knight88m** [comment]
Thanks for the fast replay, the combination with the option "Element Iframe Mode" and the Framer extension worked for me, thanks again

**Comment by sixcious** [comment]
Hi, this bug has been fixed in Version 0.8.

Thank you for reporting this Tanookirby!
