### ISSUE TITLE
problem with ublacklist app

### ISSUE THREAD

**Issue by BabyDragon5** [sixcious/infy-scroll#22]
**Describe the bug**
I use ublacklist app on Chromum
after I installed this app.
from the second page of google. "Block this site" button doesn't show up
ublacklist (https://chrome.google.com/webstore/detail/ublacklist/pncfbmialoiaghdehhbnbhkkgmjanfhe)

**URL**

**Environment**
If you can, please fill out as much as you can about your environment.
 - Device: [e.g. PC] PC
 - OS: [e.g. Windows 10] Win10
 - Browser [e.g. Chrome, Edge, Firefox] Chromum
 - Browser Version [e.g. 84.0.4147.125]
 - Extension Version [e.g. 0.1]

 **Screenshots**
https://imgur.com/a/goWw5Gu

**Comment by sixcious** [comment]
Hi BabyDragon5, thanks so much for opening this issue.

Sorry that Infy isn't playing nice with uBlacklist.

Basically, uBlacklist is expecting me to add this specific class name called `autopagerize_page_info` to Infy's page divider. Since Infy isn't AP, I don't do that. I wish uBlacklist would have instead opted to use a  [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), as the current approach assumes the user has the page divider on, and Infy lets you *not* have the divider.

However, I'll go ahead and add this class name to Infy's divider in the next release. Until then, I would recommend you use an AutoPagerize extension and not use Infy for Google Search; you can uncheck the `Auto-activate on all Database URLs` or delete the database.

**Comment by BabyDragon5** [comment]
Thanks for the answer. 
It's not a big deal for now. I will stick with your extension.

**Comment by sixcious** [comment]
Hi again BabyDragon,

This has now been addressed in Version 0.7, which is now live on all the web stores. If you still notice an issue after updating Infy to 0.7, let me know and I'll reopen this.

Thanks again for reporting this issue!
