### ISSUE TITLE
Google search breaks

### ISSUE THREAD

**Issue by Charmandrigo** [sixcious/infy-scroll#23]
**Describe the bug**
On google, without any scrolling by the user, the addon begins loading page 2 but pushes what was on page 1 (the most relevant search results) to the bottom of the page, it keeps loading more pages infinitely making you unable to see the main results from page 1

**URL**
https://www.google.com/

**Environment**
If you can, please fill out as much as you can about your environment.
 - Device: Mac
 - OS: MacOS 12.3
 - Browser Chrome 
 - Browser Version  99.0.4844.84
 - Extension Version 0.7

 **Screenshots**
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/30424766/160759763-b758b6b0-afae-4a5e-8fc3-0d84052b0c58.png">
This is the top of the google page, it immediately loaded page 2 and overlapped it on top of page 1

**Comment by sixcious** [comment]
Hi Charmandrigo,

Thanks for opening this issue. This isn't really an issue with Infy and is more about an AP Database URL not working right anymore.

I went ahead and edited the AP Database URL on your behalf. You can update your Database (in Options) or copy the XPath settings and save the URL:
http://wedata.net/items/472?rev=156639

@Tanookirby, I'm sorry for CC'ing you on this, but since you're amazingly good with XPath and happened to edit the Google Search URL recently, could you take a look at the `pageElement` for it when you have a chance? I'm not sure why the last user added a div count constraint on the rso div to be `< 2`, but unless it's `< 3` or higher it breaks with the Example URL that @Charmandrigo reported:
https://www.google.com/search?q=the+resident+joji

I'm guessing we can't just do `id('rso')/*` because Google is being a pain and making some search queries not work with that?
