### ISSUE TITLE
add another next keyword to defaults

### ISSUE THREAD

**Issue by jadedgnome** [sixcious/infy-scroll#24]
please add "show-more" to the list of default next keywords. 

the addition of the "show-more" keyword works on nitter.net urls.

https://nitter.net/Microsoft

**Comment by sixcious** [comment]
Hi jadedgnome, thanks for opening this issue and for suggesting this.

I'll have to think about this one; I'm just not sure that keywords like "Show More" and "Load More" fit as link keywords because those terms are universally used on AJAX and SPA (Single Page Application) websites for buttons that append "more" items to an existing list of items on the page, not as a link that takes you to a different page. In this case, I feel like the website isn't really using the right keyword for what it's actually doing. Adding it as a default keyword could trigger false positive links on other websites. It's a bit of a balancing act.

I'll definitely keep your suggestion in mind the next time I tweak and test the keywords. And you can always add it to your own keyword list since it's customizable.

Thanks again for the suggestion!
