### ISSUE TITLE
how can i load pages from camas.github.io/reddit-search ?

### ISSUE THREAD

**Issue by jadedgnome** [sixcious/infy-scroll#25]
I'm having trouble figuring out the rule necessary to infy-scroll on 

https://camas.github.io/reddit-search/#{%22resultSize%22:100

the xpath copied from chromium inspector gave me:
//*[@id="react-root"]/div[2]/button

**Environment**
If you can, please fill out as much as you can about your environment.
 - Device: [e.g. PC]
 - OS: [e.g. Windows 10]
 - Browser [ungoogled-chromium]
 - Browser Version [97.0.4692.71-1.1]
 - Extension Version [e.g. 0.1]

**Comment by sixcious** [comment]
Hi again jadedgnome,

Although this isn't an issue with Infy, I'll try and help. You'll want to use the Click Button action with the None append mode. There's no need to use DevTools because Infy now has a custom-made built-in Element Picker (EP). Click the EP button icon next to the Button Rule and click the "More" button on the page to generate the Selector or XPath. Here's the XPath to the button that the EP generated for me:

`id("react-root")/div[@class="flex flex-col px-auto max-w-5xl mx-auto"]/button[@class="bg-red-900 hover:bg-red-800 font-bold py-2 mb-1"]`

Since this isn't an issue with Infy Scroll, I'm going to go ahead and close this. Feel free to reply if you have any further issues though.
