### ISSUE TITLE
GitHub is behind the current store version

### ISSUE THREAD

**Issue by jadedgnome** [sixcious/infy-scroll#26]
**Describe the bug**
I downloaded the main branch zip from github and unzipped it on windows 10 to manually install it on chromium.

I loaded the unpacked extension successfully using this location 'infy-scroll-main\src\base' 

the version is 0.6 

![image](https://user-images.githubusercontent.com/2940805/162626368-e5a924e5-394a-48c5-a013-0c5b5f09ed26.png)

I realized something was amiss after getting this reply on an issue. https://github.com/sixcious/infy-scroll/issues/25#issuecomment-1093135962

I don't know how to get version 0.7.

**Environment**
 - OS: [e.g. Windows 10]
Version 97.0.4692.71 (Developer Build, ungoogled-chromium) (64-bit)

 **Screenshots**
If applicable, please add any screenshots to help explain the problem.
**However, please do not post any screenshots of the extension.** For example, please do not post screenshots of the User Interface, Options Screen, or of the Mascot Character.

**Comment by sixcious** [comment]
Hi again jadedgnome, thank you for opening this issue.

GitHub is a bit behind because I have to set aside a lot of time to review my source code to ensure I don't accidentally upload something I don't want to make public (such as some of my experimental ideas/features and some of my comments). GitHub may continue to be behind due to this. If you'd like to use the latest version, can you download it from the official browser web stores? I don't use Ungoogled Chromium, but they seem to outline some steps you can take from the link below. Could you give it a try?

https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore

I'm going to go ahead and close this, but please feel free to reply if you'd like to.
