### ISSUE TITLE
Add 1-Click Blacklist/Whitelist Buttons (temporarily disable auto-load on a page)

### ISSUE THREAD

**Issue by KinShin** [sixcious/infy-scroll#27]
**Feature request**
Please provide an option (button) to temporarily disable automatic loading on a page. A temporary disable takes effect only on that page, and the auto-load feature restarts after the page is refreshed.
Thanks.

**Comment by sixcious** [comment]
Hi KinShin, thanks for the feature request.

Infy used to have a temporary "Stop" button instead of the global "Turn Off," but I felt like the Turn Off function basically replaced the need for the Stop, so it got replaced. If you need a way to stop Infy temporarily, you could click the Turn Off button and click ACCEPT again to turn it back on. Does that not do what you're asking for?

I do plan on adding a "1-Click Blacklist/Whitelist" Button in next version. It sort of sounds like what you're looking for in that it will stop it from working on a specific URL/page; it won't be temporary, but it will be toggable.

**Comment by KinShin** [comment]
Thanks for your reply and excellent work.

I've tried many auto-page extensions and Infy Scroll is the best one I've used due to its excellent custom rules. It works perfectly on most websites, but it doesn't perform as expected on certain pages of some sites. That's why I need a temporarily disabled feature.

> I do plan on adding a "1-Click Blacklist/Whitelist" Button in the next version. It sort of sounds like what you're looking for in that it will stop it from working on a specific URL/page; it won't be temporary, but it will be toggable.

Given your statement above, I think an "exception" option associated with an 1-click toggle may solve my pain point.

**Comment by alexolog** [comment]
To add my 2 cents: the global toggle is a bit confusing, as other addons (notably ad blockers) have local switches.  It sounds like the "1-click *list" functionality that you plan to add will do just that, and the non-temporary nature of it should not be a problem as long as the icon indicates the "state" of the URL (active/disabled/no-matching-rule/etc.)

**Comment by sixcious** [comment]
Hi! A new toggable Blacklist/Whitelist button has been added in Version 8. I also made the Power button toggable so you can turn it on and off as a quick toggle. Both buttons are discrete and separate functions, and both have shortcuts that can be assigned to them. An icon and a snackbar message will appear letting you know if a site is currently blacklisted or whitelisted.

Thank you for opening this issue!  💜
