### ISSUE TITLE
How do I make it work for a specific website? (https://www.latestdeals.co.uk/deals?page=1)

### ISSUE THREAD

**Issue by privatadata** [sixcious/infy-scroll#31]
Hello there, I am trying to get the next button to load the next page and add the results under the results from the current page. Could you please tell me how this can be achieved?

**Comment by sixcious** [comment]
Hi,

Thanks for opening this issue.

Infy can work with that site. It should be finding the Next Link automatically using the default Next Rule. You could then use the Append Element mode and click the Magnifying Glass icon to use the Auto Detect Page Element feature to generate the Page Element Rule. (I would also probably trim off the last segment of it, e.g. the `/*` part.) If you'd like to save the URL, click the Heart Button to save the URL using a pattern for that specific website. Click the ACCEPT button when finished.

I'm going to go ahead close this since this isn't an issue with Infy, but feel free to reply if you still have problems.
