### ISSUE TITLE
Request: Display names of saved URLs

### ISSUE THREAD

**Issue by alexolog** [sixcious/infy-scroll#36]
**Feature request**
The "My Saved URLs" page displays the URL patterns and their dates, but not the names assigned to them.
People are better at recognizing names than regex.  Arguably they are at least as important as the dates.

**Screenshots**

![image](https://user-images.githubusercontent.com/2112513/192006426-b832491e-2d9c-421c-b6b6-89e7e719ee0b.png)

Thank you!

**Comment by sixcious** [comment]
Hi Alex,

Thanks for the feature request. In the next version update, the title (name) will show up when you hover over the URL.

**Comment by alexolog** [comment]
If a person (hi!) has a large number of saved URLs, searching by name is easier than searching by pattern, and a hover doesn't help with that.

**Comment by sixcious** [comment]
OK, this has now been implemented in Version 8. I thought this wouldn't be possible because there just isn't enough room width-wise to fit both the title and URL as separate columns, but thankfully the Material Design table rows are just tall enough to allow them both to appear vertically on top of each other.

Thanks for requesting this feature! 💜
