### ISSUE TITLE
URL List - would like to stop the Auto option when it reaches the end of the list

### ISSUE THREAD

**Issue by jddcef** [sixcious/infy-scroll#40]
I have a list of urls that I'm autopaging through, say 5 urls.
But I turn on the Auto -> Set Auto Settings, and if it's on 10 items, then it just repeats the last item over and over. 
Can't the Auto option stop if it reaches the end of the list please? So that I don't have to know exactly how many items there are each time in my list.  (Because the URL List doesn't show how items is in its list, maybe that can be added too).

As an aside, why not have an autoincrement on the URL list option too?
The auto increment option works OK, except that it changes the page url which I'm trying to avoid.

**Comment by sixcious** [comment]
Hi jddcef, thanks for opening this issue!

That's strange; you shouldn't have to worry about the Auto Times being larger than the URL List length itself. It should be adjusting the Auto Times to be the length of the URL list:

https://github.com/sixcious/infy-scroll/blob/50772b49be2c5c85c3bb1237397b4fc4bed9d448/src/base/js/popup.js#L813-L816

Now, if you decide to manually keep scrolling down after the last page Infy appends, it does currently append the last page continually. That's a separate issue and will be fixed in Version 0.8.

About your last point about, I would use the Increment URL action with Auto toggled on, and if you don't want it to update the tab's URL, uncheck the option in the `Options` > `Scroll` > `Scroll Updates` > `Address Bar (History)`.

**Comment by jddcef** [comment]
Thanks, this is great: `Options > Scroll > Scroll Updates > Address Bar (History)`, now I don't need the manual list anymore!
but could that be an option on the site config itself instead of globally maybe? Not high importance.

Great software by the way, clean stuff.

**Comment by sixcious** [comment]
Hi, in Version 8, I've made it so that the URL List mode is now no longer appending the last page continually as you scroll down. Also, you can now add the global Scroll options in Saves, but this is not exposed in the UI Window intentionally because it's not something I am 100% sure I want to officially support (and it would be a major pain to have to add all those options again in a smaller popup window).

Information about adding global options to Saves can be found here:
https://github.com/sixcious/infy-scroll/wiki/Saves

Thanks again for opening this issue! 💜
