### ISSUE TITLE
Bug: multiple saved rules not attempted for page

### ISSUE THREAD

**Issue by alexolog** [sixcious/infy-scroll#42]
When I navigate to a page that matches the urls of two saved rules, only one of them is attempted, even if it cannot find the scrollElementRule on the page.  This makes it much more difficult to make "generic" rules.

Suggestion:
* Find all the saved rules with a URL match
* Check each one in sequence, until **both** a `scrollElementRule` and a `nextSelector`/`nextXpath` are found.

I believe this is how DB rules work, I'd like saved rules to work similarly.

Thank you.

**Comment by sixcious** [comment]
Hi! OK, I've completely redesigned the way activation works in Version 8. It now ensures that the URL, action, and append settings all validate before it chooses that save to activate on. It also does multiple checks against the entire list of saves a few seconds apart (in case dynamic content appears on the page later like in #44), and on the last check it only tests that the URL matches so that it can bring up that save in the UI Window and give you a chance to edit it in case the website changed the next link/page element (this is the main reason why it worked the way it did previously).

Thanks again Alex for opening this issue! 💜
