### ISSUE TITLE
Adjust timing on when a page is checked (Presearch.com rules?)

### ISSUE THREAD

**Issue by hien4990** [sixcious/infy-scroll#44]
**Feature request**
infy doesnt work with presearch.com i tried to find their xpath but failed

**Screenshots**
https://imgur.com/a/MKmg1iV

**Comment by sixcious** [comment]
Hi, thanks very much for opening this issue.

The real problem with that site is that it adds a ~1 second delay in loading its content after the browser has finished loading the page. It is possible to add another setting to Infy to intentionally delay checking websites. I'm just not sure it's worth it, as hardly anyone would use or understand the setting.

Otherwise, Infy can technically work with that site using the Next Link action and Iframe append mode. But you would also have to add a custom script to manually change each iframe's height to about ~2500px because even iframe-resizer has trouble figuring out its height after it finishes loading.

So, unfortunately, I would classify this one as an Incompatible Website.

**Comment by zevelorgani** [comment]
> The real problem with that site is that it adds a ~1 second delay in loading its content after the browser has finished loading the page. It is possible to add another setting to Infy to intentionally delay checking websites. I'm just not sure it's worth it, as hardly anyone would use or understand the setting.

Isn't there a custom event that can be listened on?

**Comment by hien4990** [comment]
> Hi, thanks very much for opening this issue.
> 
> The real problem with that site is that it adds a ~1 second delay in loading its content after the browser has finished loading the page. It is possible to add another setting to Infy to intentionally delay checking websites. I'm just not sure it's worth it, as hardly anyone would use or understand the setting.
> 
> Otherwise, Infy can technically work with that site using the Next Link action and Iframe append mode. But you would also have to add a custom script to manually change each iframe's height to about ~2500px because even iframe-resizer has trouble figuring out its height after it finishes loading.
> 
> So, unfortunately, I would classify this one as an Incompatible Website.

thanks for your script and reply, my personally thoughts that i saw many sites  running like that  ( like coccoc search (https://coccoc.com/search)  )and future maybe many more websites will running like this so if you consider it not worth for upgrades because of these sites i appreciate it, but the extension can be more incompartible with many sites like this in the future.

**Comment by sixcious** [comment]
> Isn't there a custom event that can be listened on?

Not that I know of; Infy Scroll is injected at [document_idle](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#run_time), which happens well after regular events like [DOMContentLoaded](https://developer.mozilla.org/docs/Web/API/Window/DOMContentLoaded_event) have fired. On top of that, I've also added another 0.5 second delay before Infy starts checking the page as a precaution. Adding in a MutationObserver is a possibility, but isn't a great solution.

> thanks for your script and reply, my personally thoughts that i saw many sites running like that ( like coccoc search (https://coccoc.com/search) )and future maybe many more websites will running like this so if you consider it not worth for upgrades because of these sites i appreciate it, but the extension can be more incompartible with many sites like this in the future.

Thank you! In this case, I feel like the website is providing a bad user experience by loading its content in a delayed manner and I don't see that being a good trend that other sites want to follow in the long term. (coccoc.com is incompatible for different reasons due to being an [SPA](https://github.com/sixcious/infy-scroll/wiki/Incompatible-Websites#single-page-applications).) However, I will be adjusting the timing on when Infy Scroll activates itself for Saved URLs in the next version update, which might make it compatible with this site's delayed loading.

I'm going to go ahead and close out this issue. Thanks again.

**Comment by sixcious** [comment]
I'll reopen this until the timing change is in the next version's update.

**Comment by sixcious** [comment]
Hi again!

In the new Version 8, I redesigned Infy to now check for up to 5 seconds after the site has "loaded." For any sites that need anything beyond 5 seconds, I also added a new "Late Activation" (SPA) setting in the Scripts dialog of the UI Window.

Also, as a one-time courtesy, I added both Cốc Cốc Search and Presearch to the IS Database:
http://wedata.net/items/86111
http://wedata.net/items/86113

I'm going to go ahead and close this, but feel free to reply if there are any problems.

Thanks for opening this issue and I hope this helps!
