### ISSUE TITLE
Option to open link on current tab?

### ISSUE THREAD

**Issue by thaindq** [sixcious/infy-scroll#47]
Currently, clicking on this link will open that page on a new tab. Is there an option to open it on current tab?

![image](https://user-images.githubusercontent.com/2677309/206665860-b2dbfd9d-64f2-432e-b795-af43b65abde0.png)

The same issue also happens on any link on the newly loaded page (not on the original page)

**Comment by sixcious** [comment]
Hi ThaiN,

Thanks for opening this issue.

Under Options > EXTRA, uncheck `Open links in a new tab when clicking on them (Recommended)`. That will keep the appended page links as they originally are.

The page divider link is treated differently and is currently hardcoded to always open in a new tab. This was by design in case the user accidentally clicks on it and because I can't imagine most people are wanting to click on it. However, I can make it match what the EXTRA option is set as in the next version update.

Hope this helps!

**Comment by thaindq** [comment]
Thank you so much. Somehow I missed that option :). 

>However, I can make it match what the EXTRA option is set as in the next version update.

Yes please, having an option to toggle it would be great. I'm looking forward to it and closing this issue now.
