### ISSUE TITLE
1st page duplicated upon activation

### ISSUE THREAD

**Issue by boognish-rising** [sixcious/infy-scroll#53]
### Issue

This is not a very big deal and I was only able to look through the first page of open issues to see if it's been reported before and I wasn't able to comb through the closed issues at all but as the title suggests at least on some sites the first page is getting duplicated upon activation of the extension specifically I've noticed it consistently with amazon.com and amazon.com/vine period I have these whitelisted and everything works as expected/ intended as far as the extension activating when and where it's supposed to which is really the important part but a minor annoyance is that I always have to scroll through the first page of results again without fail. If this is something that I'm doing or not doing then I'd love to know so I can make the necessary adjustments and I wouldn't be surprised if it were user error because this extension is flawless Imo at least invaluable so if I have to put up with this minor annoyance then so be it. I'll try to determine if it's happening elsewhere, as well. 

And again, I apologize if this  has already been reported or addressed elsewhere as I had barely enough time to write this issue out let alone delve into the backlog of clothes issues ETC I thought about not leaving it until I had time to do so but all that would probably result in is me not leaving it at all so I made the Judgment call that I felt was more prudent. We'll see what hindsight has to say on the matter before too long, I suppose...

PS - I went to grab a specific URL and since Vine is an invite only program, I elected to provide an Amazon.com URL example, however I found that the issue was not presenting, so maybe it is specific to Amazon Vine, after all. In which case, I would completely understand if this falls under "can't/won't fix" for no other reason than, unless you're a "Vine Voice" (and swimming in free Amazon shite while simultaneously drowning in "items awaiting reviews"), you're hard pressed to even be able to replicate it, let alone do much about it. Either way, thanks for an awesome extension! It absolutely improves my browsing experience (i.e., improves life) several fold. 

### URL

https://www.amazon.com/vine/vine-items?queue=encore

### Version

0.7 ß

### Browser

Chrome 111.0.5563.14 (Official Build) beta (64-bit)

### OS

Noticed on ChromeOS but I think I've encountered it on Linux, as well(Arch-based distro Garuda Linux)

### Device

PC

**Comment by sixcious** [comment]
Hi boognish-rising!

Thanks for opening this issue.

As you might have guessed, I unfortunately can't access that URL, so I can't say for sure.

If I had to guess, it may be due to one of the following:
1. The `Next Link Rule` (Path) is not totally right and it needs to be replaced with a better [Path (XPath or Selector)](https://github.com/sixcious/infy-scroll/wiki/Paths-(Selector,-XPath,-JS-Path))
2. The website itself is incorrectly linking Page 2 to go to Page 1; try clicking on the "Page 2" link and see if it actually does go to Page 2 (and also that Page 2 doesn't have Page 1's content)

Is this a Database URL? If so, you can try [AutoPagerize](https://chrome.google.com/webstore/detail/autopagerize/igiofjhpmpihnifddepnpngfjhkfenbp) and see if it exhibits the same behavior. If it's exhibiting the same problem, then it's possibly due to one of the two reasons above. If it's not, then it's an issue with Infy, but not something I think I can fix unless I have an accessible URL.

I hope this helps a little!
