### ISSUE TITLE
This site does not scroll?

### ISSUE THREAD

**Issue by salviox** [sixcious/infy-scroll#57]
### Feature Request

Try this,
If you can scroll it ,teach me how.
Thanks.

https://space.bilibili.com/510856133/video

**Comment by sixcious** [comment]
Hi salviox!

This isn't really a feature request, but I'll try to help. That's an AJAX website, so you'll need to use Version 0.8's new AJAX append mode. Specifically, you'll need to use the Click Element Action and the AJAX append mode.

Version 0.8 is currently only on GitHub as a preview/test. If you'd like to try it, instructions are below. Otherwise, you'll need to wait for it to be released to the web stores.
https://github.com/sixcious/infy-scroll#installation

As a one time courtesy, and because I haven't yet finished documenting how the AJAX append mode works, I've added this site to the IS Database for you:
http://wedata.net/items/86109

I hope this helps.
