### ISSUE TITLE
How to set up Infiny Scroll for leboncoin.fr website, element cannot be selected

### ISSUE THREAD

**Issue by oeloo** [sixcious/infy-scroll#60]
### Problem

Hi, despite selecting the 'Next Link' and the 'Page Element Rule' it is always written "A Next Link wasn't found. Try another or adjust the Next Rule" and "No elements were found. Try adjusting the Page Element Rule" :
![image](https://github.com/sixcious/infy-scroll/assets/98819304/c16e4d55-6c3a-4946-ad4a-1fa04ceecc9c)
I do not get how to set up Infy Scroll to work on leboncoin.fr website.

I have also see that this website is registered on wedata.net : http://wedata.net/items/55198
but I have the impression this setting is not used.

### URL

https://www.leboncoin.fr/recherche?text=enfant&locations=r_19&page=6

### Version

0.7

### Browser

Chrome Version 113.0.5672.127 (Official Build) (64-bit)

### OS

Windows 11 22H2

### Device

PC

**Comment by oeloo** [comment]
It does not work properly with Page as you get this:
![image](https://github.com/sixcious/infy-scroll/assets/98819304/5a9a5db9-29d4-401c-88fc-6dec4363fc0b)
I have entered the same config as you:
![image](https://github.com/sixcious/infy-scroll/assets/98819304/297437c4-53f2-4254-a41f-b409fcd82430)

**Comment by sixcious** [comment]
Hi oeloo!

Although this is not an issue with Infy, I'll try and help you with that site as a one-time courtesy. That site loads very slow for me and uses a script to lazy-load its images, so you'll want to use the Element Iframe mode; both `trim` or `import` would work.

I've added this site to the IS Database on your behalf because it uses a non-standard AP key:
http://wedata.net/items/86125

If you don't want to wait for the database to update, go to Options > Saves > Add Save > and copy/paste the following to add that site to your Saves:

````
{
  "action": "next",
  "append": "element",
  "date": "2023-05-26T18:35:08.330Z",
  "name": "Leboncoin",
  "nextLink": "//a[@title='Page suivante']",
  "pageElement": "//div[@class='src__Box-sc-10d053g-0 cnsuKn']/*",
  "pageElementIframe": "import",
  "url": "^https://www\\.leboncoin\\.fr/recherche?"
}
````

I'll go ahead and close this, but feel free to reply if you still need help.
Thanks!

**Comment by oeloo** [comment]
Thank you, I have entered the JSON inside the Infy extension, it looks great.

How long does it take for changes in the database http://wedata.net/databases/InfyScroll/items to be usable by the Infy Scroll extension ?

**Comment by sixcious** [comment]
Hi! It depends on the download location you've set in the Database Options, but it usually takes about ~1 day for the CDNs (jsdelivr.net, statically.io) to update when changes are made to wedata.net.
