### ISSUE TITLE
Infy not working on enhanced google searches

### ISSUE THREAD

**Issue by ibay770** [sixcious/infy-scroll#62]
### Problem

First, many thanks for making an awesome extension.
It's not working on sites with custom google searches (https://www.searchcraigslist.net/results?q=car)
as one example. I tried using the element picker, but no dice so I thought maybe, I'd ask the expert :)

Thanks in advance.

### Device

None

**Comment by sixcious** [comment]
Hi Nossy!

Thank you so much.  Although this isn't an issue with Infy, I'll try my best to help you with that site as a one-time courtesy.

That's an AJAX site, and it's a pretty nasty one because it refreshes itself when iframes are appended. So, AJAX Iframe is out and that leaves AJAX Native. AJAX Native is Infy's most advanced append mode, but it's still in proof-of-concept status, and it won't work perfectly. You'll notice some slight flashing, because that's what the site normally does each time the next button is clicked.

I've added this site to the IS Database on your behalf:
http://wedata.net/items/86128

Go to Options > Databases. Change the Download Location to wedata.net, re-download the InfyScroll database, then change the download location back to jsdelivr.net (or whatever you had set it to before).

If it's not working to your liking, click the toolbar icon and blacklist the Database URL. AJAX Native is going to be one of my main topics of research for the next version of Infy, but I'm not sure when that will be.

Hope this helps. 💜

**Comment by ibay770** [comment]
Thank you very much! It works great! Sure there's some slight flashing but its nothing major. I"m impressed with how you can look at any site, and be like, sure this is how you do it.
Much appreciated.

**Comment by sixcious** [comment]
Hi ibay, sorry for the long delay! I've added custom style/CSS support in Version 8, so the flashing effect should now be gone from this site.
Thank you very much! 💜

**Comment by ibay770** [comment]
> Hi ibay, sorry for the long delay! I've added custom style/CSS support in Version 8, so the flashing effect should now be gone from this site.
> Thank you very much! 💜 
 Thank **you** very much!
You do better for no charge what some companies can't do for money! Appreciate your drive and response to feedback! 
I am curious how you got so good with programming. I'm in awe of how you can just look at a site and immediately figure how to configure it. 
Thank you very much again for making my life easier!
