### ISSUE TITLE
Tooltip issues

### ISSUE THREAD

**Issue by wordpure** [sixcious/infy-scroll#64]
### Problem

1. Prompt will not adjust position according to window edge

	![图片](https://github.com/sixcious/infy-scroll/assets/68013962/11fd430d-5dbc-464e-8b4a-10008d0086cf)

	![图片](https://github.com/sixcious/infy-scroll/assets/68013962/1eb457fc-ba2c-43fb-952b-935f688fd5f3)

2. Text with a hint is center-aligned instead of left-aligneAlignment of one tooltip text is centered instead of left justified for other tooltips
	
	![图片](https://github.com/sixcious/infy-scroll/assets/68013962/9c5f0bfb-8549-4d0e-8534-9c07b7f3b968)

### URL

irrelevant

### Version

0.8

### Browser

Firefox 114

### OS

Windows 11

### Device

PC

**Comment by sixcious** [comment]
Hi again wordpure, thank you for opening this issue!

1. Yes, I'm aware of this one. I use [balloon.css](https://github.com/kazzkiq/balloon.css) for tooltips, and unfortunately, while minimal, it's a pure CSS library, so it doesn't contain JavaScript logic to reposition tooltips, and so sometimes [they might not fit on the user's screen](https://github.com/kazzkiq/balloon.css/issues/153). There's really not much I can do unless I change to a JavaScript tooltip library like [Tippy](https://github.com/atomiks/tippyjs) or [Floating UI](https://github.com/floating-ui/floating-ui), which would be a big task. I was considering using Material Design's own tooltips, but that was a very, very long-term goal. Your second screenshot is only an issue for `zh`/`zh_CN` though it would be resolved by me changing to a JS library. (This is what it looks like in English.)

![Capture](https://github.com/sixcious/infy-scroll/assets/1027814/e186563c-58a1-4ea6-a797-6029af3c09e6)

2. Yes, I remember that one; it was a bit of a pain to add a tooltip for that specific Material button, since it also opens a dialog. I updated the CSS here on GitHub, so it's left-aligned now and will be ready for the next version of Infy.

I'll give this tooltip repositioning issue some more thought whenever I can come back to work on Infy.

Thank you! 💜

**Comment by sixcious** [comment]
Hi again!

Sorry for the long delay. This should now be resolved in the latest version of Infy Scroll that was released last week (Version 8). It's now using a custom implementation of [Floating UI](https://github.com/floating-ui/floating-ui) tooltips, which is based on JavaScript, and can calculate where the tooltip can fit and what direction is should be displayed automatically.

Thank you again for reporting this issue, wordpure! ❤️
