### ISSUE TITLE
Add support for amazon vine pages

### ISSUE THREAD

**Issue by JS-1982** [sixcious/infy-scroll#67]
### Feature Request

While Infy Scroll seems to work for regular amazon webpages, it does not seem to work for the Vine section of amazon. The URL structure looks like this: https://www.amazon.de/vine/vine-items?queue=encore&pn=&cn=&page=2 or https://www.amazon.de/vine/vine-items?queue=encore&pn=562066&cn=&page=2, whereas the “queue” variable (“=encore” in this example) may also vary (and also be “=last_chance” or “=potluck”). Any chance to enable Infy Scroll for this?

**Comment by alexolog** [comment]
It also did not work well when choosing an order other than the default (say, ordering by rating or price).

**Comment by sixcious** [comment]
Hi JS!

Thank you for opening this issue. Unfortunately, I don't have access to Amazon Vine URLs . The good news is that I designed Infy so that you can make it work yourself by using its UI. You don't have to rely on me or even the databases to make it work. Also, see #53 where someone asked about that same website and I provided some suggestions to try. Feel free to let me know if there's anything I can help you with.

> It also did not work well when choosing an order other than the default (say, ordering by rating or price).

Alex, you just need to save the URL with the `Watch for changes on the page to help enable late activation (AJAX/SPA)` setting in the Scripts dialog found in the UI Window. See my https://github.com/sixcious/infy-scroll/issues/51#issuecomment-1445430644 where you brought this up a while back. If you still have problems, we can discuss in a separate issue.

Thank you! 💜

**Comment by meinname** [comment]
just seen this issue. 

It works great for me with this on the german Amazon vine:
```
{
  "id": 1,
  "name": "Amazon Vine - Club der Produkttester",
  "url": "https://www.amazon.de/vine/vine-items?queue=encore",
  "type": "pattern",
  "date": "2023-05-25T16:33:27.382Z",
  "action": "next",
  "append": "element",
  "nextLinkKeyword": true,
  "nextLink": "#vvp-items-grid-container > div.a-text-center > ul.a-pagination > li.a-last > a",
  "pageElement": "#vvp-items-grid > *"
}
```
Maybe with replacing .de by .com it works for the US version

**Comment by JS-1982** [comment]
Thanks!
