### ISSUE TITLE
Not loading the Rashi commentary, not sure how to activate that.

### ISSUE THREAD

**Issue by ibay770** [sixcious/infy-scroll#68]
### Problem

On [this](https://www.chabad.org/library/bible_cdo/aid/15785) site, I tried using the next page setting, which works, but it doesn't load with Rashis commentary ( the url is set to true at the end but I don't know how to append the next page with that setting) 
Thanks in advance.

### Device

None

**Comment by sixcious** [comment]
Hi again Nossy!

OK, there's two things going on with that site:
1. It's using a script to load its commentary so you'll need to use the regular Iframe append mode instead of Page to load that script for all appended pages.
2. It only updates the next link to show the commentary for the link that's visible on the page (not the link that Infy tries to find automatically), so you'll need to explicitly give it a path to the specific link that it's updating to enable the commentary.

Try copy/pasting the below Save for that site and add to your Saves by going to Infy Scroll's `Options > Saves > Add Save` (if you already have a Save made for the site, you can delete or edit it):

````
{
  "action": "next",
  "append": "iframe",
  "name": "Chabad",
  "nextLink": "//a[@class='next_article']",
  "type": "regex",
  "url": "^https://www\\.chabad\\.org/library/bible_cdo/aid/"
}
````

Like I mentioned in #62 though, this is really the last time I can help you with a specific website. I'm just one person, and there's so many websites out there that I can't really (set a precedent to) provide support to everyone who needs help with a site (as much as I'd like to!). Thank you for understanding. 💜 

I'm going to close this, but I really hope this helps. Thank you! 💜

**Comment by alexolog** [comment]
While I understand your reasoning, saying "this is really the last time I can help you with a specific website" sends the wrong message.
It will be better to give people a venue to ask for and to contribute entries, either via [GitHub discussions](https://docs.github.com/en/get-started/quickstart/communicating-on-github#github-discussions) or a link to an external forum.

**Comment by ibay770** [comment]
Just wanted to thank you again. You're right, it's true you are only one person and obviously you are not expected to help out, you have indeed done so much. The reason we turn to you is cuz you're the expert, it's like busy specialists that are always busy because they are so good. 
Perhaps as @alexolog mentioned, perhaps make another discussion board where people can post problem sites and others can fix them.
Thank you again for everything.

**Comment by ibay770** [comment]
> While I understand your reasoning, saying "this is really the last time I can help you with a specific website" sends the wrong message. It will be better to give people a venue to ask for and to contribute entries, either via [GitHub discussions](https://docs.github.com/en/get-started/quickstart/communicating-on-github#github-discussions) or a link to an external forum.
What would be a good forum to use for this?

**Comment by sixcious** [comment]
Hi, sorry for the super long delay. I can't think of a forum suited for this aside from something like Stack Overflow, but I created a Discord to help field these types of questions, which I'm now linking to in the Options Screen and Help Guide.

I hope that is satisfactory and I appreciate your understanding 💜
