### ISSUE TITLE
save URL dialogue renders cut-off so I can't see all the buttons

### ISSUE THREAD

**Issue by wang-d** [sixcious/infy-scroll#69]
### Problem

See the screenshot below.  I think there are meant to be more buttons but I can't figure out how to scroll down to see them.  I can select them by tabbing past the pattern/regular expression/exact choice.

![image](https://github.com/sixcious/infy-scroll/assets/3472168/df15b095-757b-4350-a307-ba6134a448e6)

I tried hovering my mouse by the right edge to see if a scroll bar would appear.  None does.

I tried typing Page Down while the focus was on a control in this dialogue.  No response.

I tried zooming the page using Ctrl-minus and Ctrl-plus.  The website behind the dialogue zooms, but the dialogue itself remains unchanged.

I think whatever controls are being hidden are necessary to finish saving a website.  If I click out of the dialogue and then reload the saved URLs page of the Infy Scroll extension preferences I see that I have no websites saved.

Possibly relevant: my screen is 1366 x 768 .

How do I finish saving a URL?

### URL

https://www.google.com/search?channel=fs&client=ubuntu-sn&q=ubuntu+screenshot

### Version

0.8

### Browser

Firefox 117.0 (64-bit)

### OS

ubuntu 22.04 LTS

### Device

PC

**Comment by sixcious** [comment]
Hi, thank you for opening this issue!

Sadly, this is really a Firefox specific problem and there isn't much I can do. Firefox will automatically cut-off/crop the Popup  Window if there isn't enough height to display it without allowing it to overflow gracefully via scrollbars. It's actually a known bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1748411

This is in contrast to Chromium, which honors the height and overflow properties that are set, so scrollbars appear in the UI in both the Popup Window and in the MD Dialog. Here's how it looks like in Chromium under the worst case (to show that this is really a Firefox issue):
![Capture](https://github.com/sixcious/infy-scroll/assets/1027814/410fb61c-3fa2-4743-af53-6fad211eb318)

I can't really tell from your screenshot because it's not a full window snip, but 766px should be enough height. Infy only uses a 599px Popup Window, but that's assuming a 100% Display Scale Factor. If you're using something higher like a 125% scale, then that combined with the low 766px resolution and Firefox's handling of the Popup Window might be why you're encountering this issue. Until Firefox fixes the issue, my best suggestion would be to try lowering your scale factor or increase the resolution temporarily so that you can save the URL.

Sorry for the inconvenience, I hope this helps 💜

**Comment by wang-d** [comment]
Thanks for the investigation and the detailed response.

> 768px should be enough height. Infy only uses a 599px Popup Window,

Not sure what's going on.  I don't have any display scaling on the built-in screen.

Luckily even my 10 year old laptop can output 4k over DP so I can still save URLs on my external monitor.
