### ISSUE TITLE
What settings are required to work on this particular site?

### ISSUE THREAD

**Issue by Tenome** [sixcious/infy-scroll#77]
### Problem

I'm trying to load the next pages of Mangadex, but can't seem to get it working. I have Xframey installed as well whenever I try it. The pages increment. I'm trying to get this working for the Library page specifically, but you need an account to see that. It seems to work the same way though.

https://mangadex.org/titles/latest
https://mangadex.org/titles/latest?page=2

etc

### URL

https://mangadex.org/titles/latest

### Version

0.8

### Browser

Firefox Developer 121.0b9

### OS

Windows 10

### Device

PC

**Comment by sixcious** [comment]
Hi Tenome!

I can try helping you with the URL you provided (as a one-time courtesy).

You're on the right path, although it might not be the most efficient. Yes, you could use Xframey to append iframes. Then you'd use the `Next Link` action (Infy should find the link using a default keyword `arrowright`) and `Element` append mode (check `Element Iframe`). You could then simply use the [Element Picker](https://github.com/sixcious/infy-scroll/wiki/Element-Picker#how-to-find-the-page-element-using-the-ep) to pick the nearest parent of the page elements.

However, this is actually an AJAX site, and so I'd use the [AJAX Native](https://github.com/sixcious/infy-scroll/wiki/AJAX#ajax-native) append mode, although it's still in proof-of-concept status and may not work perfectly (in this case, the page dividers might stay at the bottom). Since AJAX Native doesn't require Xframey, I've added this site to the InfyScroll Database on your behalf:

http://wedata.net/items/86195

The database should auto-update for you within the next couple days. You can get it immediately by going to `Options` > `Databases` and changing your `Download Location` to `wedata.net` and manually downloading it, then changing it back to the original location (e.g. `jsdelivr.net`).

If you're not happy with the way it works, you can blacklist it and use your own Saved URL, using the Iframe/Xframey approach.

Lastly, just as a heads up: that site isn't designed very nicely and most pages have different HTML structures, even if they might look similar. It was not trivial for me to write robust paths for it, so if you're not familiar with Selectors or XPath, you'll want to look at a tutorial or read the [Paths](https://github.com/sixcious/infy-scroll/wiki/Paths-(Selector,-XPath,-JS-Path)) section if you'd like to make it work with other parts of the site.

I hope this helps! 💜

**Comment by Tenome** [comment]
Ahh, no wonder I couldn't get it working, it's Ajax. I didn't try that. Thanks for the help, and for adding it as an option!
