### ISSUE TITLE
Add support for fshare site folder

### ISSUE THREAD

**Issue by BoscoFZ** [sixcious/infy-scroll#78]
### Problem
The problem I encounter when I assign a click event to the load more button to display more items, everything is ok on the pages that have the item, but when I scroll to the last page of the site, the site will reload and display null items. Can you please help me rewrite a better rule so that it doesn't make the same error as mine. Thank you very much.

This is the rule I tried

```
{
   "action": "click",
   "append": "element",
   "clickElement": "button.mdc-button.mdc-button--raised.button-load.ng-binding",
   "comment": "https://github.com/sixcious/infy-scroll/issues/62",
   "date": "2023-12-19T18:55:27.703Z",
   "id": 23,
   "lazyLoad": "auto",
   "name": "Fshare - - NETFLIX - IQiyi- Viet Sub - Fshare",
   "pageElement": "div.list.mdc-detail-list.down-folder",
   "type": "regex",
   "url": "^https?://www\.fshare\.vn/*"
}
```

Example: with url https://www.fshare.vn/folder/H7DXADP8PMOA

With the first scroll, the page display items is ok

<a href="https://upanh.org/image/gVdgct"><img src="https://i.upanh.org/2023/12/23/chrome_MVhHUdtbMNc832b2474acc4dd9.md.png" alt="chrome_MVhHUdtbMNc832b2474acc4dd9.md.png" border="0"></a>

But when i scroll to the last page, the page will display null item

<a href="https://upanh.org/image/gVdUU0"><img src="https://i.upanh.org/2023/12/23/chrome_Be3NKEJenJ730287c2e54e7edc.md.png" alt="chrome_Be3NKEJenJ730287c2e54e7edc.md.png" border="0"></a>

### URL
https://www.fshare.vn/folder/H7DXADP8PMOA or https://www.fshare.vn/folder/PQB4C5D7L6QW

### Version
0.8

### Browser
Chrome 120.0.6099.130 
Firefox Esr 115.6.0

**Comment by sixcious** [comment]
Hi BoscoFZ!

I can try helping you with that website (as a one-time courtesy). However, this isn't really a feature request. Could you please go back and edit your post and add in all the required information from the [Problem Report](https://github.com/sixcious/infy-scroll/issues/new?template=problem_report.yml) template as it is laid out so I can better assist you? Please do **not** create a new issue, just [edit your post](https://github.com/sixcious/infy-scroll/issues/78#issue-2049303747) here (or add a new comment in this issue) and add in all the information from the Problem Report template I linked to.

Thank you! 💜

**Comment by BoscoFZ** [comment]
Thank you for your suggestion and I have edited my post above. Sorry for the inconvenience.

**Comment by sixcious** [comment]
Hi again BoscoFZ!

As a one-time courtesy, I've gone ahead and added this website to the InfyScroll Database on your behalf:
http://wedata.net/items/86197

The strategy I used was to copy and compare the HTML of the button when it is both visible and hidden, using my browser's [DevTools](https://github.com/sixcious/infy-scroll/wiki/DevTools). When the button is hidden, the site adds a class called `ng-hide`, which we can use to filter it out from our working path:
````
<button class="mdc-button mdc-button--raised button-load ng-binding ng-hide" ng-show="$ctrl.next != '' &amp;&amp; !$ctrl.busy" ng-click="$ctrl.nextPage('')">
  Xem Thêm
</button>
`````

So, in the case of your `clickElement` CSS Selector, just add a `:not(.ng-hide)`, like so:
````
button.mdc-button.mdc-button--raised.button-load.ng-binding:not(.ng-hide)
````

Also, for your `pageElement` CSS Selector, I would recommmend adding a ` > *` to the end so the page divider is appended in the correct position. That would look like:
````
div.list.mdc-detail-list.down-folder > *
````

###### Important Note
There will always be a new page divider added at the end for an additional page at the bottom. This is due to the complexity of the app's workflow when the action is `click` and the append mode is `element`. It actually needs to be done in reverse order and it needs to prepend the divider before checking for and doing the click to avoid a race condition with the website. So, this is sort of intentional, but it might be something I might spend some time to prevent in a future version of Infy. If it bothers you, you can change the Append Mode to `none` and it won't append any dividers at all for a (cleaner look).

Let me know if this helps! 💜

**Comment by BoscoFZ** [comment]
Hi sixcious,
I followed your suggestion and the infy scroll worked great. Thank you very much for your support.
