### ISSUE TITLE
Forum Thread Print View

### ISSUE THREAD

**Issue by poa00** [sixcious/infy-scroll#79]
### Problem

Is there a way I can add a pattern to the database for print view URLs?  Infy Scroll works perfectly with the specific forum for which I installed it initially, but just not when in print view.   I would totally settle for list view; however, even with the requirements in your documentation met, a list of 3 URL for instance, will scroll infinitely (just repeating those same URL over and over since the thread ends after three pages). The URL for print view is almost identical, save for the view=print parameter appended to the end of the URL and no links, which I believe is the the problem. 

Here is an example of the URL for the first few pages of a thread, demonstrating the pattern:
|Page  |                   URL pattern                                                                         |
|    :--  |                :--                   |
| **1** | `...com/boards/viewtopic.php?f=6&t=45307&view=print`                  |
| **2** | `...com/boards/viewtopic.php?f=6&t=45307&start=20&view=print` |
| **3** | `...com/boards/viewtopic.php?f=6&t=45307&start=40&view=print` |
 
So, `&start=20` is appended to Page 2's URL ( page two will start with post #20), and `&start=40` is appended to Page 3's URL (page three will start with post #40) and so on. Is there any workaround I could use?

### URL

www.autohotkey.com/boards/viewtopic.php?f=6&t=45307&view=print

### Version

Just installed it today (so newest)

### Browser

Edge Version 120.0.2210.91 (Official build) (64-bit) 

### OS

Windows 11 Enterprise

### Device

PC

**Comment by sixcious** [comment]
Hi poa00!

I can try to help you with this specific website (as a one-time courtesy).

So, as you mentioned, the website doesn't provide a next link in its print view, so you'll need to use a different action. Luckily, Infy has an `increment` action I designed for situations just like this.  I've created a Saved URL item just for you so you can simply copy and paste it and add it as a [Save in the Options Screen](https://github.com/sixcious/infy-scroll/wiki/Saves#adding-saves-from-the-options-screen) (again, this is being done as a one-time courtesy just for you):

````
{
  "action": "increment",
  "append": "element",
  "base": 10,
  "interval": 20,
  "name": "AutoHotkey Community • View Print",
  "pageElement": "id('page-body')/*",
  "selectionStrategy": "smart",
  "url": "https?://www\\.autohotkey\\.com/boards/viewtopic.php?.*start=\\d+&view=print"
}
````

Anytime you want to add infinite scrolling in print view, you'll just need to edit the URL to add the `start=0&view=print` parameters to the end of it so it picks up the URL pattern. Also, note that if you continue to scroll past the actual last page Infy will continue to append it again, so you'll want to stop at the last page. This is not a bug and is due to the website responding like this when a request is made with a `start` value that is higher than the thread's post count. If you have any questions about these settings, feel free to reply, but they should be covered in the Help Guide (I recommend reading the Actions, Paths, and Saves sections).

I hope this helps! 💜

**Comment by poa00** [comment]
Thanks @sixcious !!  This is much appreciated. 😀

**Comment by poa00** [comment]
works PERFECTLY. Thanks again!!
