### ISSUE TITLE
Quest about keywords at Next Link Settings

### ISSUE THREAD

**Issue by BoscoFZ** [sixcious/infy-scroll#80]
### Problem

Hi, I have a question about keywords at Next Link Settings.

I see you have a suggestion in the keywords section that says "Keywords are ordered in priority, separated by commas, all lowercase, and should not contain spaces, dashes, or underscores"

So in case my keywords are words like Next, Next ›, Next →, NEXT... like it's all upcase or capital letters or has spaces, in these cases can Infy support more or i must write my own rules for these cases.

Thank you so much

### URL

https://en.btdig.com/search?q=john+wick

### Version

0.8

### Browser

Chrome

### OS

Window 10

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related with the app and is not related to making it work with a specific website

**Comment by sixcious** [comment]
Hi again BoscoFZ, thanks for opening this issue!

There's no need for you to add any extra keywords to account for variations involving uppercase letters, spaces, dashes, or underscores. Behind the scenes, when Infy scans the website's HTML for keywords, it normalizes all of it - lowercasing it and removing all the aforementioned characters - so that it will match the lowercased keyword exactly. Therefore, you should always keep your keywords lowercased and without spaces.

For example, if the website has the following HTML, which has an uppercase `N` and a space between the word and arrow:
````<a href="/page2">Next →</a>````

During the scanning process, Infy automatically converts it to look like this, lowercasing the `n` and removing the space, so it will match the default `next→` keyword:
````<a href="/page2">next→</a>````

I'll add an extra sentence on that screen explaining this so it's more clear.

I hope this helps! 💜
