### ISSUE TITLE
Ability to add empty space for fixing out-bounds elements (Add Custom Styles/CSS Option)

### ISSUE THREAD

**Issue by ilias-7565** [sixcious/infy-scroll#83]
### Feature Request

Some websites don't fully work on small screenes. As an example, in landscape mode on a phone, use search on https://developer.mozilla.org/en-US/docs/Web , you won't be able to get all it's results.

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my feature request is an actual feature that can be added into the app and is not related to making it work with a specific website

**Comment by sixcious** [comment]
Hi ilias-7565, thanks for opening this issue!

I don't quite understand your feature request; could you please elaborate and provide a screenshot of the problem, as well as the Saved URL object you are using and your device specs to help show what you mean? MDN is an AJAX site and I have no issues with getting all the search results to display properly using the Click Action and AJAX Append Mode on a mobile device in landscape mode.

For context, here's what I'm seeing on a very small Pixel phone:
![Screenshot](https://github.com/sixcious/infy-scroll/assets/1027814/55f63cda-570c-4727-9f3e-56b46b02b46a)

Also, if you need to add some empty space or alter the CSS in any way to make it work with your device, you could use a [Userstyle or Userscript Manager](https://github.com/sixcious/infy-scroll/wiki/Scripts-and-Styles#custom-styles). (I would recommend trying Stylus first.)

I hope this helps. 💜

**Comment by ilias-7565** [comment]
Don't press Enter, try using the pop-up list on small screen.

**Comment by sixcious** [comment]
I don't have an Enter key to press as I'm testing this all on a mobile device.  As I kindly asked, could you please provide a screenshot showing the problem, the Saved URL settings you are using, and your mobile device's specifications (resolution, OS, and browser) so I can try and help you?

**Comment by ilias-7565** [comment]
![Screenshot_20240218-122204_Firefox](https://github.com/sixcious/infy-scroll/assets/66683424/d08523a4-851c-47eb-9519-607c7c374ecd)

**Comment by sixcious** [comment]
Hi again ilias-7565,

OK, it took me a really long time to figure out what you were actually referring to. I don't think this is related to Infy Scroll. The grey "pop-up" search results is MDN's own web design, and the same thing happens without using Infy Scroll. Please contact Mozilla and [open an issue](https://github.com/mdn/yari/issues/new/choose) to let them know so they can fix it. Or you can use a Userstyle Manager like [Stylus](https://addons.mozilla.org/addon/styl-us/) to add the CSS to fix it. Unfortunately, this feature really falls outside the scope of functionality of what Infy Scroll does.

Sorry, I know that's not what you were hoping to hear, but I really hope that helps. 💜

**Comment by ilias-7565** [comment]
Ik that its probably not what you meant when have chosen the name for addon, but you could add the infy scroll margins capability too :) . Its up to you though, you can close this Issue if you want, this functionality isn't required. Adding Stylus only for this, also on mobile, is a bit too much.

**Comment by sixcious** [comment]
I totally get where you're coming from! 💜 It seems like it's a simple margin issue, but that `div.search-results` popup on MDN's site is positioned absolutely, and since each site is different, it's really going to require some custom CSS or JS to fix. Google has become a lot more strict with MV3 and I'm worried they might consider something like that to be remote code execution. If I were to add that in via the new [chrome.userScripts](https://developer.chrome.com/docs/extensions/reference/api/userScripts) API, it could creep on violating their [Single-use policy](https://developer.chrome.com/docs/webstore/program-policies/quality-guidelines-faq#single-purpose) because Infy is not really a userstyle or userscript manager like Stylus and ViolentMonkey are.

I plan on reevaluating custom CSS/JS in the future to see if it can be allowed. I honestly think the best option is to open an issue with the website/MDN because it's their own code and you shouldn't have to put up with using a 3rd party app to fix it 💜

**Comment by ilias-7565** [comment]
I didn't know about the google thing. I totally agree that they should fix it, but that has high chance of happening on other sites. Hoping and waiting for devs of each site to fix it isn't very logical.

**Comment by sixcious** [comment]
Hi again, sorry for the delay!

I personally spoke with the Chrome team, and they let me know that custom CSS is now allowed in Manifest V3. So I've added a new Custom Styles/CSS option found in the Scripts and Styles dialog in Version 8, which I released last week. I hope this helps.

Thank you for making this feature request! 💜
