### ISSUE TITLE
Issue with resizing images

### ISSUE THREAD

**Issue by grubhg** [sixcious/infy-scroll#85]
### Description

Good day.

Sorry for the burner account.
I have an issue with resizing when trying to use infy in order to read webcomics/manga online.
In the attached screenshot will be an example.
![image](https://github.com/sixcious/infy-scroll/assets/169207454/a8e95894-24a0-496c-8304-3191aa01f221)
1 - First page of the chapter
2 - Second page of the chapter
The exact issue is, that the first page loaded is the expected size, and all subsequent images of the chapter loaded are at a fixed smaller size, that do not readjust even with zoom tools such as ctrl+mousewheel. (well they do readjust, to keep being small)

Is there a way to tweak this in the options? I had a look over the available settings and couldn't seem to find something that'd help.
I saw there was a recent (2 days ago) review on the chrome extension store regarding this issue as well, and I imagine it's the same issue I am experiencing.

### URL

NSFW URL

### Version

 Infy Scroll BETA Version 0.8 β

### Browser

OperaGX

### OS

Windows10

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related with the app and is not related to making it work with a specific website

**Comment by sixcious** [comment]
Hi grubhg, thank you for opening this issue! 💜 

There's a checkbox under `OPTIONS` > `EXTRA` > `Resize images and media that are bigger than the page (Recommended)` that you can uncheck to disable this. It's a global setting; here's a screenshot showing where it's located:

![Resize Media Options](https://github.com/sixcious/infy-scroll/assets/1027814/01d383e8-3086-4812-bfb5-0e44ec407b67)

> I saw there was a recent (2 days ago) review on the chrome extension store regarding this issue as well, and I imagine it's the same issue I am experiencing.

I was *totally* assuming that was you up till I got to this part! Since you're now the second person to have issues with the resize images setting, I went ahead and tested it again just now to make sure, but it tested fine for me unfortunately.

Does that help resolve the issue?

**Comment by grubhg** [comment]
I have this setting turned off already unfortunately.
I figured out however, that zooming in to 500% kinda breaks it and makes it viewable. So there is that.
I do have a work around now with that.

**Comment by sixcious** [comment]
I'm guessing the NSFW website doesn't have any comics/manga that are SFW or relatively tame/mild? If not, could you post an example NSFW URL in an HTML comment, like this by surrounding it with `<!--` and `-->` so that [it shows up hidden](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#hiding-content-with-comments)?

````
URL: <!-- https://www.nsfw-website.com/nsfw-manga -->
````

##### Example (Rendered Output)
URL: 

If that works, I can try taking a look to see what's going on!

**Comment by grubhg** [comment]
Sure can.
This one is mostly sfw, well, I wouldn't recommend reading it at work, though.
URL:

**Comment by sixcious** [comment]
Thanks, I can see the URL! 👍 

OK, so I know it appears that way, but Infy isn't actually doing any resizing on this site. What's happening is the site initially loads the images in the smaller size you're seeing. The site then loads its own "resizing" script to make the images bigger.

When Infy appends the next page, it isn't allowed to append the scripts for that page ([Google disallows this, sadly](https://developer.chrome.com/docs/extensions/develop/migrate/remote-hosted-code#i-was-told-my-extension-has-rhc-whats-going-on)), so the appended pages are stuck in their "initial" small state.

To help show this isn't a problem specific to Infy Scroll, this is how [AutoPagerize](https://chromewebstore.google.com/detail/autopagerize/igiofjhpmpihnifddepnpngfjhkfenbp) behaves when it appends Page 2:

![AutoPagerize Example Screenshot](https://github.com/sixcious/infy-scroll/assets/1027814/d9cf5703-f629-4843-8e95-0f016f47eaee)

A simple solution is to not have it append the offending div (`image-container`) for each page to begin with. This can be done by adjusting the `Page Element Path` and adding `/*`. Since this is an AutoPagerize Database URL, I've gone ahead and edited it for you on your behalf:

<details>
  <summary>Link</summary>
  <a href="http://wedata.net/items/76720?rev=157894">http://wedata.net/items/76720?rev=157894</a>
</details>

You can download the updated database now if you go to `OPTIONS` > `DATABASES` and change the `Database Location` to `wedata.net`, or you can wait a couple days for it to happen automatically, or you can save the URL with the change locally.

This is how it looks for me after making the change.

Let me know if this resolves your issue! 💜

![Infy Scroll Example Screenshot](https://github.com/sixcious/infy-scroll/assets/1027814/bba1d18e-07b1-4303-afda-ab3fa98e2a62)

**Comment by grubhg** [comment]
![image](https://github.com/sixcious/infy-scroll/assets/169207454/2437caa9-4a47-48e2-971d-2fb7ac6c5abe)

It appears that updating the database resulted in images being displayed infinitely next to each other rather than horizontally.

**Comment by sixcious** [comment]
That's also because you're not using the page divider (which is on by default), which forces the images to break. For a perfect solution without the page divider, you can:

1. Use the `Element Iframe` append mode so that the site's resize image script loads. However, you'll also need to install something like [Xframey](https://github.com/sixcious/xframey) to allow iframes to load on the site because it disallows them.
2. Use a user style extension like Stylus and override the site's styling for the `image-container` div that is making them small to begin with. (Again, this is the site resizing the images, not Infy Scroll.)

I went ahead and reverted that database item back to its original settings since they don't seem to work for your requirements.

I hope that helps you.

**Comment by grubhg** [comment]
Thanks for all the effort.
What you suggested is working well.
