### ISSUE TITLE
Why does using Iframe mode cause the page to scroll continuously on my device?

### ISSUE THREAD

**Issue by xiaoyuhaoge** [sixcious/infy-scroll#86]
### Description

Hi, thanks for the extension, I really like its features! It works well with simple websites, but once I use the Iframe mode, and then slide the page to a certain position, it will cause the page to continue scrolling and cannot stop, which confuses me🤔Is it because I am using a mobile device? I really can't rule out the reason myself, so I came to ask for help, because it is not only on this website, but also on other websites using Iframe. I recorded a video so that you can see its error

https://github.com/sixcious/infy-scroll/assets/134502767/86b7a0ae-416b-449c-bdd0-d8edfa107046

### URL

https://orionfeedback.org/

### Version

0.8

### Browser

Orion 

### OS

ios 

### Device

Phone

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related with the app and is not related to making it work with a specific website

**Comment by sixcious** [comment]
Hi xiaoyuhaoge, thank you so much for your kind words and for opening this issue! 💜 

Are you using the Database URL settings I made for you from the Discord, which uses the `Element Iframe` append mode?

When the append mode is `Element Iframe`, Infy has to scroll the iframe so that the lazily loaded images are loaded. The iframe is hidden though, so it shouldn't be scrolling your window. This issue may be specific to iOS Safari/Orion because it works fine on Android browsers.

Try saving the URL by clicking the Heart Button. Then go to `OPTIONS` > `SAVES` and edit the Save and add the [scrollIframeEnabled](https://github.com/sixcious/infy-scroll/wiki/Saves#other-keys) key and set it to `false`. So, your Save would look something like this (you could copy/paste this instead if you wanted):

````
{
  "action": "next",
  "append": "element",
  "name": "Orion Public Issue Tracker",
  "nextLink": "//*[@rel='next']",
  "pageElement": "//ul[@class='DiscussionList-discussions']/*",
  "pageElementIframe": "import",
  "scrollIframeEnabled": false,
  "url": "^https://orionfeedback\\.org/"
}
````

Please let me know if that works. 💜
