### ISSUE TITLE
Cannot block additional Elements from being Loaded

### ISSUE THREAD

**Issue by Arun10752** [sixcious/infy-scroll#88]
### Description

#infy-scroll-page-2 > .maincontainer > .middle > .side-bar

#infy-scroll-page-2 > .maincontainer > .middle > .main-content > .browsediv > .recimg

#infy-scroll-page-2 > .maincontainer > .middle > .main-content > .browsediv > .recdiv

#sub-header

These Elements are Loading in all pages while infy scroll Paginates, How to block this behavior and Make Infy Scroll only Load Contents

For Example, I only want this to be Loaded

#infy-scroll-page-2 > .maincontainer > .middle > .main-content > .browsediv > .browsetablediv > .belowheading > .browsetableinside

Please fix, thanks

### URL

[Redacted]

### Version

Latest

### Browser

Chromium 109

### OS

Windows 8.1

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related with the app and is not related to making it work with a specific website

**Comment by sixcious** [comment]
Hi Arun10752, thank you for opening this issue.

I'm sorry, but I had to redact the URL you posted because it looks to be a NSFW URL.

Here are some suggestions you can try:

1. Use the `Element` append mode and provide a `Page Element Path` to only the element(s) you want appended, but make sure not to include `infy-scroll` specific elements in the path. So, your `Page Element Path` could be (based on your post): `.maincontainer > .middle > .main-content > .browsediv > .browsetablediv > .belowheading > .browsetableinside`. 

2. Use a content blocker. [uBlock Origin](https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) has a `Pick` option that lets you use an Element Picker to create filters for the elements you don't want appended and will block them.

I hope this helps. 💜

**Comment by Arun10752** [comment]
i think you did something in the backend, Now it works, Thanks

But Still missing the ability to activate/turn on infinite scrolling using context menu/Right click menu

Example, Right click on an empty area in a website and you will see -> Back, Forward, Reload, Save as, Print..etc(I want Infy Settings control there)

**Comment by sixcious** [comment]
I'm glad you got it working! Checking the Database Stats, it looks like Griever3 added this URL to the AutoPagerize Database on your behalf, so credit and thanks to them. 🎉

I'll go ahead and close this since this you've got this resolved.

> But Still missing the ability to activate/turn on infinite scrolling using context menu/Right click menu

This is a good idea. I'm slightly hesitant to add this because a lot of people are sensitive to apps cluttering their context menu. The new "limited height" (scrollable) context menu Chrome recently introduced in 2023 amplifies this moreso. It would also require adding an extra permission (`contextMenus`) and I was hoping to keep the permissions as minimal/simple as possible. I'll notate this though and consider implementing it in the future as an option, especially if more people request this. 💜
