### ISSUE TITLE
Can't get it working on Alibaba

### ISSUE THREAD

**Issue by ghuznee** [sixcious/infy-scroll#89]
### Description

I search for a keyword and brings up the key results but I can't get it working

### URL

https://www.alibaba.com/trade/search?spm=a2700.details.pageModule_fy23_pc_search_bar.keydown__Enter&tab=all&SearchText=yoga+mats

### Version

Latest

### Browser

Latest Chrome

### OS

Macbook

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related with the app and is not related to making it work with a specific website

**Comment by sixcious** [comment]
Hi ghuznee, thanks for opening this issue.

That site doesn't use links, so you'll want to use the `Click Element` action and `AJAX` append mode. You can use the Element Picker to generate a path for the `Click Element Path` to the `>` button at the bottom of the page. You'll also need to install [Xframey](https://github.com/sixcious/xframey) to allow Iframes to work.

If you need more help, please check the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) since this is about help with a website. You can try asking your question on the Discord or any of the resources listed.

I hope this helps you.💜
