### ISSUE TITLE
Bing Search - Doesn't load favicon images

### ISSUE THREAD

**Issue by sridhars650** [sixcious/infy-scroll#92]
### Description

<img width="1005" alt="Screenshot 2024-07-07 at 1 19 19 PM" src="https://github.com/sixcious/infy-scroll/assets/164981605/d08dd68f-e81b-4ace-9f4a-1393b58f6734">
As you can see, the first page has favicon images but second one doesn't.

### URL

https://www.bing.com/search?q=What+is+pokemon&qs=n&sp=-1&ghc=1&lq=0&pq=what+is+pokemo&sc=11-14&sk=&cvid=988C3874BECC46ADBA760971AE4EB1B4&ghsh=0&ghacc=0&ghpl=&FPIG=7F9F0BC1D3B241E6BE0E5AA4F7A8E617%2c8CCB3303E9C641E783BF0FBE838FACE2&first=25&FORM=PORE

### Version

0.8

### Browser

Chrome 126.0.6478.127

### OS

macOS Sonoma

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related with the app and is not related to making it work with a specific website

**Comment by sridhars650** [comment]
<img width="1339" alt="Screenshot 2024-07-08 at 9 37 25 AM" src="https://github.com/sixcious/infy-scroll/assets/164981605/95e67f71-18df-490b-968b-25258219b848">
Also video thumbnails don't load

**Comment by sixcious** [comment]
Hi sridhars650, thanks for opening this issue 💜 

Although this isn't really an issue with Infy and is about help with making it work with a specific website, I can help you with this site as a one-time courtesy.

If you see a site having any type of image issues, it's almost always because it uses a script to generate them. The easiest way to fix these issues is to use an Iframe append mode so that the scripts load. So, for your specific Bing website example, since it's already using the `Element` append mode, just check `Element Iframe` in the Popup UI Window and then Save the URL so it remembers that setting.

Please let me know if that works for you.

If you'd like more information, I also cover this subject more in-depth in the Help Guide: [Missing Images or Blank Pages](https://github.com/sixcious/infy-scroll/wiki/Missing-Images-or-Blank-Pages).
