### ISSUE TITLE
Change the popup window default view to show the buttons if the URL is already recognized

### ISSUE THREAD

**Issue by DandyClubs** [sixcious/infy-scroll#97]
### Description

1. if Not On 

 setup PopUI when Infy Scroll icon click 

2. show Turn On Off icon when cancle click

3. i want to direct show Turn On/Off when toolbar Infy Scroll icon click 

and

4. disappears rule setup UI Popup when lost tab focus (window.onblur)

5. need keep Popup before close by user

https://github.com/user-attachments/assets/6b7345e0-fba4-4ca3-a6ce-8749318feb6a

### URL

ex

### Version

8

### Browser

firefox edge

### OS

windows 11

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related to the app and is not related to making it work with a specific website (including [how to make images load](https://github.com/sixcious/infy-scroll/wiki/Missing-Images-or-Blank-Pages))

**Comment by sixcious** [comment]
Hi again DandyClubs, thanks for opening this issue and for the video 💜 

> 1 2 3

When the app isn't enabled (**ON**) on a specific site/tab, the assumption is that you want to set it up, not turn it off, as it is not turned on yet for the tab, and it doesn't make sense to show the buttons at that point. What is your use-case for wanting to have immediate access to the Power Off Button when it is not turned on for the current tab?

> 4 5

Yes, I totally understand and agree. The browser controls how the Popup closes and I have no control over this unfortunately. I don't save your changes until you click the **ACCEPT Button** due to how complex the app is and due to the sheer number of settings, as well as needing to validate your settings all at once. I understand your issue though and I'll keep this in mind for the future.

Does this helps explain things? Please let me know if you have any other questions!

**Comment by DandyClubs** [comment]
1.

i make new site rules... but somesite not ON 

The URL matches but does not turn on.

same nextLink and  pageElement 

Try xpath But Not Work.  Icon Off

Try Select But Not Work.  Icon Off

Try "append": "ajax", Mode Icon ON


https://yandex.com/search/?text=aaa&lr=10635&search_source=yacom_desktop_common

{
  "id": 10,
  "name": "Yandex",
  "url": "https://yandex.com/search?text",
  "type": "pattern",
  "date": "2024-10-02T11:56:28.302Z",
  "action": "next",
  "append": "element",
  "duplicateStop": true,
  "nextLink": "//div[@class ='Pager-Content']/div[./a[@class='Pager-Item_current']]/following-sibling::div[1]/a",
  "pageElement": "//div[@class='main__center']/div[@class='main__container']/div[@class='main__content']/div[@class='content i-bem']/div[@class='content__left']"
}


Icon Not ON


2. 

If you change from Off to ON need direct Infy scroll On/Off and blacklist On/Off

**Comment by sixcious** [comment]
Hi again! Well, that save has no chance of working with the example URL you posted because it won't match the URL. The `url` pattern should be: `https://yandex.com/search/?text`.  (Note the missing `/` inside the `search?` part.) Also, from what I'm experiencing, that's a pretty hostile/defensive site that does checks to ensure you're not loading the next page too quickly.

If that isn't the issue, then I'm real sorry because I don't think I understand what you're trying to say in English. Can you write your post in your native language so I can machine translate it?

**Comment by DandyClubs** [comment]
규칙이 존재하는 페이지의 경우 ON 일때

일시적으로 OFF 로 변경하고 난 후..

다시 ON을 하려고 하면

규칙생성 창이 나타납니다.

**Comment by sixcious** [comment]
Hi, I'm going to try and summarize your use-case:

1. It is currently ON
2. The user turns it OFF
3. The user closes the Popup
4. The user re-opens the Popup and wishes to see the Buttons (not the Setup)

If so, I can make it re-open the Popup showing the Buttons, so long as it was previously ON at least once.

Please confirm if that is correct and acceptable.

**Comment by DandyClubs** [comment]
Yes!

   1. It is currently ON
   2. The user turns it OFF
   3. i want  show  ON/Off Button if already has Site Rule

**Comment by sixcious** [comment]
Hi again DandyClubs, I published a new version of Infy Scroll this week on the web stores (v8.1) and the Popup window's default view should now work as you described.

Please let me know if you experience any issues.

Thanks for your patience and for opening this issue 💜
